### ISSUE TITLE
Unify name of website

### ISSUE THREAD

**Issue by 7coil** [Terminal/ls.terminal.ink#130]
unfortunately dapps seems to have at least 30 different names

just switch languages and look at the nav bar

liste d'applications discord
discord bot list
discord apps marketplace
discord bot liste von terminal.ink

**Comment by Saederup92** [comment]
Why not just name it something like "discord app list" or something similar?

**Comment by 7coil** [comment]
Discord Apps

**Comment by 7coil** [comment]
but correctly translated

**Comment by cyyynthia** [comment]
I'll give a look to french translations tomorrow and update stuff

**Comment by 7coil** [comment]
Most site titles have been changed to `Discord Apps` now, with some localisations

![image](https://user-images.githubusercontent.com/13886925/57156327-96625880-6dd5-11e9-81dd-f28b8f23c6ab.png)
![image](https://user-images.githubusercontent.com/13886925/57156334-995d4900-6dd5-11e9-87fa-82d70ba440f2.png)

At least they are consistent in their own languages
