### ISSUE TITLE
Title keeps changing!

### ISSUE THREAD

**Issue by sleeplesskyru** [Terminal/ls.terminal.ink#206]
I changed the HTML title in `index`. When I refresh the page, the title says what I want at first but then changes back to "Discord Apps"... You can see this is a problem as my community is not called "Discord Apps"

**Comment by 7coil** [comment]
React helmet controls the <title> element, and the one in the HTML file is just simply a placeholder

**Comment by 7coil** [comment]
Also this is not a problem with the website.

**Comment by sleeplesskyru** [comment]
Didn't say it was a problem with the website, just a problem in general that I did not know how to fix... But thank you for the fast response, I will go try that :D
