### ISSUE TITLE
why i got automatically banned when i join the support server

### ISSUE THREAD

**Issue by YasmijnVels** [Terminal/ls.terminal.ink#207]
I want to join the server and get banned automatically!
I don't think that's the intention!
my discord name is: LDS # 8264

![image](https://user-images.githubusercontent.com/59023524/74829071-85f17f00-5310-11ea-89c4-1b31224297aa.png)

**Comment by 7coil** [comment]
The owner of the server (not me) has made it such that super new accounts can't join.
I'll work out a solution

**Comment by 7coil** [comment]
The issues area however, is not for issues about the server.

**Comment by 7coil** [comment]
@YasmijnVels It should be okay now.
