### ISSUE TITLE
Design Bugs

### ISSUE THREAD

**Issue by aki-jp** [Terminal/ls.terminal.ink#60]
> Site is too simplistic. Easy to get confused.
> Doesn't say whether short description needs to be within 10 and 100 words or characters.

> Nice errors

![](http://aki-toga.tk/ss/cj7qc.png)

**Comment by lepon01** [comment]
Please elaborate with "Site is too simplistic"

Where do you think the site is too simple?
Please enter screenshots

**Comment by aki-jp** [comment]
`Add Language` button is not explained. I thought it was to add what language the bot was, rather than description.

**Comment by Andre601** [comment]
I don't see your issue....
Imo is a well-explained page much more useful than one that has just text fields and buttons with stuff that doesn't explain a little thing.
Also if it was for the **library** the bot uses, then it would clearly show **library** and not **language**

Also, this description here does imo explain it more than enough
![image](https://user-images.githubusercontent.com/11576465/49741966-e0686780-fc97-11e8-81f8-9b27a8e90d58.png)

**Comment by lepon01** [comment]
![verbose](https://user-images.githubusercontent.com/13886925/49749464-4e189180-fca0-11e8-824b-b2bd9fba38cf.png)
![V E R B O S E](https://user-images.githubusercontent.com/13886925/49749471-51ac1880-fca0-11e8-95b7-f623766ae1b6.png)

**Comment by aki-jp** [comment]
@Andre601 You see, the site is so simplistic you can miss such little details.

**Comment by lepon01** [comment]
You want it to look... More complicated?

**Comment by aki-jp** [comment]
With such a simple site, the big text stands out the most and can take away the user's attention off the smaller text. Font size on the information text should be increased or the title font size decreased.

**Comment by lepon01** [comment]
What would you think these should read

**Comment by aki-jp** [comment]
The latest changes are fine.
What I'd like to see is more equalized fonts so users can't miss important information.
